# Generated by Django 4.1.6 on 2026-07-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_reviewstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="statement",
            field=models.TextField(blank=True, default=""),
        ),
    ]
