# Generated by Django 4.1.6 on 2024-08-10 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('leetcode_url', models.URLField(unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=7)),
                ('category', models.CharField(choices=[('arrays-hashing', 'Arrays and Hashing'), ('two-pointers', 'Two Pointers'), ('sliding-window', 'Sliding Window'), ('stack', 'Stack'), ('binary-search', 'Binary Search'), ('linked-list', 'Linked List'), ('trees', 'Trees'), ('heap-pq', 'Heap / Priority Queue'), ('backtracking', 'Backtracking'), ('tries', 'Tries'), ('graphs', 'Graphs'), ('advanced-graphs', 'Advanced Graphs'), ('dynamic-1d', '1-D Dynamic Programming'), ('dynamic-2d', '2-D Dynamic Programming'), ('greedy', 'Greedy'), ('intervals', 'Intervals'), ('math-geom', 'Math and Geometry'), ('bit-manip', 'Bit Manipulation')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=7)),
                ('time_taken', models.PositiveIntegerField(help_text='Time taken in minutes')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem', 'date_time')},
            },
        ),
    ]
